# Generated by Django 5.0.4 on 2024-04-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_password_token',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
